Friendship v2
SevlaMare/social-team pull request #4
Opened 2020-06-12 16:43 UTC by SevlaMare

2020-06-16 21:42 UTC, mosesogwo requested changes
**Hi @SevlaMare, @rsnazario :clap: Good work :+1:**
What you need to do now is:

- [x] Move updating friendship acceptance status and creating 2nd row of friendship from friendships controller into a friendship model method.

- [x] Sent friend requests, incoming friend requests and confirmed friends should be collected using SQL queries instead of querying the database from your views. You should use associations similar to those provided below to implement this:
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

```ruby
# User model

# Users who requested to be friends - friend requests
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
- [x] Use the above associations in friendships index instead of the conditional checks you currently have.

- [x] After sending a friend request, the button for the friend still appears as "Add friend", the button should be removed or be modified to show the status of the friendship.

- [x] Add tests for the features implemented in this milestone.



_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-06-16 21:42 UTC, mosesogwo commented on app/controllers/posts_controller.rb
>    end
Move timeline_posts functionality into a model method.
It could be something similar to this:
```
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
end

```

2020-06-16 21:42 UTC, mosesogwo commented on app/controllers/posts_controller.rb
>    end
Use this User model method to retrieve posts for Post index controller

2020-06-16 21:42 UTC, mosesogwo commented on app/models/friendship.rb
> +  scope :my_friends, ->(id) { where('friend_id =?', id) }
Replace unused scope definitions with the associations with SQL queries provided for pending_friendship, inverted friendship, confirmed friendship.

2020-06-19 03:41 UTC, Anna-Myzukina commented
## Hi team! Very nice project! :wave: 

# [APPROVED]  :+1:

### Go and merge to Develop.


`Goodluck in your next Milestone | Happy coding ` <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"><img class="emoji" alt="computer" height="25" width="25" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png"></g-emoji>

2020-06-19 14:08 UTC, merged